### ISSUE TITLE
Installing Helix into my project

### ISSUE THREAD

**Issue by amazing-Mantse** [Lokeh/helix#5]
I am installing `helix` into an app that is already using `hx`

I have included the library as so:
`lilactown/helix                {:mvn/version "0.0.6"}`

Requiring `[helix.core :refer [defnc]]` throws the error bellow:

` [Figwheel:WARNING] Could not Analyze: /_SLASH_impl_SLASH_class/js.cljs is not a relative path  resources/public/js/helix/core.cljs   
[Figwheel:SEVERE] java.lang.IllegalArgumentException: /_SLASH_impl_SLASH_class/js.cljs is not a relative path
`

This basically applies to requiring anything.

**Comment by Lokeh** [comment]
I haven't tested helix in a figwheel project. Can you tell me what version of figwheel you're using? A minimal repro would be very appreciated.

**Comment by amazing-Mantse** [comment]
I am using figwheel version "0.2.3" and I run it with the following **options** 
  `--main figwheel.main --compile-opts {:source-map,true} . --build common --repl`

**Comment by amazing-Mantse** [comment]
@Lokeh what do you mean a minimal repro? Do you mean in a new clojure project?

**Comment by amazing-Mantse** [comment]
@Lokeh here is a minimal hello_world project with figwheel and helix. Still getting the same error.

https://github.com/amazing-Mantse/figwheel-helix

![image](https://user-images.githubusercontent.com/11287538/72419702-0ce98f80-3786-11ea-8589-204e291663e9.png)

**Comment by Lokeh** [comment]
Thanks, the minimal example did help.

I created a new branch here: https://github.com/Lokeh/helix/tree/fix-figwheel

There were some additional problems in your minimal repro about `"react"` that I'm not sure right now how to fix.

Also, unfortunately my current fix in that branch is running into this bug in shadow-cljs https://github.com/thheller/shadow-cljs/issues/638 which prevents me from releasing it at this time.

**Comment by amazing-Mantse** [comment]
Thank you very much.I will checkout the branch.

**Comment by amazing-Mantse** [comment]
Hi, I have updated the minimal app (https://github.com/amazing-Mantse/figwheel-helix) and fixed the react issues. From `helix.core` I get the error bellow: 

![image](https://user-images.githubusercontent.com/11287538/74019621-9fa1d680-49a0-11ea-95e2-70f5c98c83d6.png)

**Comment by Lokeh** [comment]
@amazing-Mantse I've merged the `fix-figwheel` branch with master, which removes that require.

**Comment by amazing-Mantse** [comment]
Okay, but now I am back to the original error:

I added the dependancy as so : 
`Lokeh/helix                       {:git/url "https://github.com/Lokeh/helix"
                                           :sha     "cfb99f8936aa8d7f71f9759a81a93df9cb4a1772"}}
` and now I have this error: 

![image](https://user-images.githubusercontent.com/11287538/74445728-88bb2280-4e7f-11ea-9434-e0be82386f5f.png)

**Comment by Lokeh** [comment]
I've updated the `fix-figwheel` branch with a few more adjustments.

Here's an example repo using it: https://github.com/Lokeh/fighweel-helix

It's based off of your repo @amazing-Mantse, there was some misconfiguration that I fixed along with updating to the latest git SHA.

**Comment by danieroux** [comment]
Thank you, Figwheel works with this. 

The next challenge is advanced compilation which fails with:

```
ERROR: JSC_LANGUAGE_FEATURE. This language feature is only supported for ECMASCRIPT6 mode or better
```

I've pushed an example of that to https://github.com/amazing-Mantse/figwheel-helix 

And it can be replicated with:

```
clojure --main cljs.main --compile-opts common.cljs.edn --compile-opts '{:optimizations :advanced}' --compile
```

**Comment by Lokeh** [comment]
helix's implementation uses several ES6 features - specifically, the `class` keyword. You'll want to configure your release step to set `:language-in :es6` at the least.

**Comment by amazing-Mantse** [comment]
@Lokeh Thank you very mush for making `helix` work with `Figwheel`. We have successfully managed to incorporate it, into our project. And it's looking great. We still have a few `hx` components, but we are transitioning.

**Comment by Lokeh** [comment]
hooray!

**Comment by deoqc** [comment]
Hello!! Thx for the great library @Lokeh 

Tried w/:
```clojure
Lokeh/helix {:git/url "https://github.com/Lokeh/helix"
                       :sha "56ff32df5ca270aac7b63d6ad55adb9c2318f61d"}
```

but it is throwing `Error building classpath. Destination path "helix" already exists and is not an empty directory`.

Any ideias/help?

**Comment by Lokeh** [comment]
@deoqc this looks like a problem with your local deps. Perhaps try clearing your deps cache? If you keep running into this, please open another issue.

For figwheel usage, I will continue to rebase https://github.com/Lokeh/helix/pull/26 onto master for the time being until I can merge them. Figwheel users should check that PR to get the latest version compatible.
